"""
Django settings for djangointermediario project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '77u)f1lj@_p6(rza(_zp7=wq6mhic-%@@emh2c8%^#epo5bpl_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # o * faz  a aplicação funcionr com qualquer host


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base2', # Criado com (django-admin startapp base2)
    'bootstrap4', # Instalado com (django-bootstrap4)
    'stdimage', # Instalado com (django-stdimage)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware', #Só será preciso quando o app for ser publicado na produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangointermediario.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], # Será usado um diretorio chamado 'templates'
        'APP_DIRS': True, # Que ficará dentro do diretorio de aplicações
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangointermediario.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Seta-se o drive que a aplicação irá usar, na frente de backends
        'NAME': 'djangointermediario', # Seta-se um nome para o banco de dados
        'USER': 'root', # Seta-se um usuário para o banco de dados
        'PASSWORD': '', # Seta-se uma senha de acesso ao banco de dados
        'HOST': 'localhost', # Seta-se o hosto do banco de dados. Usa-se localhost por padrão
        'PORT': '3306', #seta-se uma porta para o banco de dados
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #coleta todos os arquivos estaticos
#da nossa aplicação e colca dentro de 'staticfiles'
MEDIA_URL = 'media/' # Utiliza esse diretorio para fazer uploud de arquivos de midia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ________Configuração de E-mail____________: --- Usado no desenvolvimento
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Essa configuração infora ao django que, embora não tendo um servidor de E-mail, o 
# Django deve deixar a aplicação pronta para e-mails, para quando ela tiver um servidor de e-mails.
# Isto é, o Django simula que está recebendo um e-mail e printa-o no console. Se o envio do e-mail funcionar, 
# se o django printar no console, quer dizer que a aplicação está pronta para receber um servidor de e-mails


# _________Configuração para quando tivermos um servidor de e-mails____________: --- Usado na produção
"""
EMAIL_HOST = 'localhost'
EMAIL_HOST_USER = 'no-replay@seudominio.com.br'  ---# E-mail usado geralmente para se conectar ao servidor de e-mails
EMAIL_PORT = 587   ---# Se for conexão segura, geralmente será '587'
EMAIL_USER_TLS = True   ---# Se vai utilizar criptografia ou não, mas geralmente sim
EMAIL_HOST_PASSWORD = 'sua-senha'   ---# Senha do email 'no-replay'
"""
